### ISSUE TITLE
S8R not able to discover RB-20 telemetry sensors

### ISSUE THREAD

**Issue by DaySpeed955i** [FrSkyRC/Firmware-Test#10]
This is a know problem dating before V2.0.1 FCC
Same thing with V2.1.0 FCC, only sensor OC20 is discovered from RB-20

All other sensor connected to RB-20 are discovered normally with S8R.

**Comment by Adelaxie** [comment]
Confirmed, thanks.

**Comment by Adelaxie** [comment]
confirmed and please check #13 as a brief conclusion
