### ISSUE TITLE
Random occurrence of "sensor lost" in ACCESS 2.1.7

### ISSUE THREAD

**Issue by ululi1970** [FrSkyRC/Firmware-Test#120]
RX SR10 Pro, FW 2.1.7
TX Horus X10S, OTX

After updating RX FW from 2.1.6 to 2.1.7 I started getting random "sensor lost" warnings during flight. The lost sensor is a air speed indicator. The sensor is a SP-ASS-70, almost new. 
Never had any problem when running 2.1.6. For the moment, I downgraded to 2.1.6

**Comment by Adelaxie** [comment]
same issue with #121 
please check there for update.
