### ISSUE TITLE
S8R not moving surfaces during Self Check when using SBUS

### ISSUE THREAD

**Issue by DaySpeed955i** [FrSkyRC/Firmware-Test#16]
When servos are connected to S8R, all surfaces move at the end of Self Check.

When using SBUS connected to RB-20 or SBUS to PWM decoder, servos are not moving at the end of Self Check. Self Check is ending normally and S8R is working as expected.

Same behavior with previous firmware.
Tested with Quick Mode enable and disable.

**Comment by Adelaxie** [comment]
Confirmed , please follow #13 for issue fixing updates.
