### ISSUE TITLE
Initialization time S8R Quick mode

### ISSUE THREAD

**Issue by hobby1946** [FrSkyRC/Firmware-Test#21]
With V2.1.0 some servos of the S8R in Quickmode twitch 2x or run into the end position.
This is caused by a needle impulse after about 1-2 s .
After that there are no pulses for 4 seconds !

This is not the case in the V2.0.1. There this pulse also occurs.
But immediately after that ( approx. 1ms ) the regular servo pulses come,
so that this impulse does not come to fruition.
The output level is approx. 2v until the servo signals come.
They arrive after only 2 s !

With V2.1.0 this pulse does NOT occur if the SxR function is disabled !
Not even if the SxR Function is enabled and the Quickmode is disabled !
In this case the RX is ready for operation even after 2s.
If the SxR-Mode is enabled and the Quick-Mode is enabled, then this needle pulse appears briefly and after another 4s the servo pulses appear.
Here the blue LED flashes as before until the servo pulses are output.

This Quick Mode should be improved as soon as possible.

The blue flashing was already before. There were also problems.

In addition an initialization time of approx. 6 s is much too long.
If the receiver stops once because of undervoltage, it takes 6s until the model is controllable again,
if it's still "alive" then ! 

The auto mode is ok.

**Comment by Adelaxie** [comment]
Please check #13 for the updates.
its the same issue than #3
