### ISSUE TITLE
S8R quickmode startup time too long

### ISSUE THREAD

**Issue by Gewe99** [FrSkyRC/Firmware-Test#3]
Receiver: S8R: In quick mode, the blue LED flashes for 5s after power on . 
Control of the servos is not possible during this phase.  If you switchQuickmode  off , the startup time is less than 1 second. This is ok.
The startup time in Quickmode is definitely too long! This is problematic when CPU is reset by e.g. watchdog or voltage peaks...

**Comment by digitalonkel** [comment]
I can confirm the issue above. The S6R is much faster, less than a second.
In addition one of the channels goes to full deflection during the long 5s startup of the S8R
Regards Rainer

**Comment by Adelaxie** [comment]
to be reproduced.

**Comment by Gewe99** [comment]
I just checkes the S6R.
The Quickmode startuptime is Ok.

**Comment by digitalonkel** [comment]
That's what I said. S6R ist fast, but S8R is to slow.

**Comment by LapinFou** [comment]
Same on my side: S6R is fast, however S8R is very slow.
This also true with the latest ACCST v1 firmwares.

**Comment by LapinFou** [comment]
@Gewe99 Could you add **S8R** in the title of this ticket.

**Comment by Adelaxie** [comment]
confirmed and please check #13 as a brief conclusion
