### ISSUE TITLE
ISRM-S-X10S_2.1.0_200515Beta FW

### ISSUE THREAD

**Issue by hpolig** [FrSkyRC/Firmware-Test#43]
The external antenna of the X10S is active when I switch it off in OpenTx 2.3.7 and vice versa.

If I remove the antenna in "switched on" state nothing happens now, no warning
and RSSI remains the same. If I remove the ext. antenna in the "switched off" state there is still
no warning but the RSSI drops from almost 90 to 50-55 in my living room test

**Comment by Tiefflieger68** [comment]
I can confirm this.

In case of disactivated, but mounted extenal antenna, I have an RSSI of 90db.
(distance 3m - RX6R with latest ACCESS FW)
Everything seems fine.
Now I unmount the external antenna and RSSI drops to 44db. Ups...

In case of activated external antenna, I have a RSSI of 90db. No matter if external antenna is mounted or not. 

2 ideas:
1: there is an issue at the ISRM firmware
2: the antenne ports of the module have changed. In this case you have to change the install video

**Comment by Tiefflieger68** [comment]
looks good !

test1: 
- external antenna mounted
- external antenna switched off (in TX options)
RSSI 90
- unmount external antenna
no changes at RSSI
everything as expected

test2:
- NO external antenna mounted
switch on external antenna.
Got Warning 
everything as expected

test3:
- mounting Terminating Resistor insted of antenna
switch to external antenna
RSSI drops to 50 und loose connection at distance larger 10meters
this test shows there is no internal antenna active
everything as expected

well done guys !

**Comment by Adelaxie** [comment]
Check the CODE section to get the latest firmware, thanks.
The antenna working mode was wrong, very sorry about that.
Function tests continue.

**Comment by proublot** [comment]
Hello,
I made 5 flights yesterday with the firmware of May 18 in ACCST mode and I have a very good RSSI compared to the original module of my X12S.

**Comment by proublot** [comment]
The RSSI of my X6R in V2.1.0 with my X12S upgraded ISRM-S-X10S
https://i65.servimg.com/u/f65/16/46/22/07/rssi_y10.png
