### ISSUE TITLE
No FrameLost bit set G-RX8_ACCST_2.1.0_LBT20200519

### ISSUE THREAD

**Issue by zufus** [FrSkyRC/Firmware-Test#55]
Hi, 

according to some reports posted on rcgroups.com and to the log reported below, the latest firmware does not set the frame-lost bit.

I can't believe there are not FL bit set with the RSSI values reported here....

As you can verify in the attached log (sensor value 5102) there have been several intervals with > 4 consecutive lost frames.

This is dangerous, as it potentially makes any redundancy system totally useless.

Thanks

Marco
![G_RX8_NO_FL_set_ACCST_2 1 0_200519_LBT](https://user-images.githubusercontent.com/1472448/82841933-0b6c6880-9ed8-11ea-8baf-fe40987c0cb9.PNG)
[TripletSpeed-2020-05-24.zip](https://github.com/FrSkyRC/Firmware-Test/files/4678763/TripletSpeed-2020-05-24.zip)

**Comment by VancouverUmbrella** [comment]
The attached flight data also shows that the FL bit (5100) was not set even though 300ms of zero link quality were recorded by the 5103 sensor at just before the 18:52:00 time.

Shouldn't the FS bit also have been set for this zero link quality occurrence? 

![image](https://user-images.githubusercontent.com/56514835/82843027-a2153700-9e90-11ea-98ea-c037d4d2ad9a.png)

[Sky_2m-2020-05-22.1.fixed.csv.zip](https://github.com/FrSkyRC/Firmware-Test/files/4678826/Sky_2m-2020-05-22.1.fixed.csv.zip)

Best,
Andrew

**Comment by Allerhopp** [comment]
RX8R_ACCST_2.1.0_LBT.frk
Same behavior. No lost frames reported in SBus.

**Comment by franz4949** [comment]
Manipulated FL bit in SBus stream is a general mess in all ACCST firmware. This makes all flight controllers work faulty with its evaluation of link quality. Is it this what FrSky wants? FrSky should be very carefully with trying to fool its users, users are not stupid and will take notice of such for their future decisions. FrSky is strongly advised to stop this manipulation and release clean firmware which does not manipulate the FL bit. All receivers shall have that clean and honest firmware. Please go and take according corrective action.

**Comment by Adelaxie** [comment]
Fixed in v2.1.2 G-RX8 firmware

**Comment by mpjf01** [comment]
Have any of the test group actually tested 2.1.2? Did that release resolve the issue mentioned above as well as those apparent in 2.1.0 and 2.1.1?
