### ISSUE TITLE
G-RX8 Beta Firmware PWM Issue

### ISSUE THREAD

**Issue by bitzerjd99** [FrSkyRC/Firmware-Test#65]
Flashed my G-RX8 to the newest Beta Software (for testing) and could not get it to go into PWM mode (to support Channel 7).  Used the ACCESS version.  It was registered and bound with the Channel 1/2 jumper.  Once I downgraded it to the Released Version (on the Frsky Site) it worked fine.

**Comment by Adelaxie** [comment]
Try without channel 1/2 shorted. We modify the behavior as suggested by this version.
