### ISSUE TITLE
New Archer M+ no RSSI FPort

### ISSUE THREAD

**Issue by QuadStryke** [FrSkyRC/Firmware-Test#79]
Hello,

I am actually very mad and I will describe the problems that I'm having with the brand new AM+: First, I bought the Xm+. And guess what, Frsky fcked up the firmware. There's an issue on github where people have 80 and lower rssi while standing next to the quad and extremely low rssi when flying away. Anyways, Frsky did not manage to fix it. So I thought well, I'll go buy the new AM+ Access and there won't be any problems. But again, Frsky fcked it up.
My FC is a Crazybee F4R V3. I soldered a cable from TX1 to the inverted S.port. I get stick inputs and everything is fine. Except Rssi.
I chose FPort in Betaflight, enabled telemetry etc. Normally you should get rssi instantly. But guess what - didn't work. I don't get any rssi signal, it's always 0. If I program a RSSI input and mixer in Otx, it works. But with FPort you are supposed to disbale rssi aux, which I did, and all the other things I've mentioned before (enable telemetry etc.). Why would I use FPort when the I can't get the benefits of not having to program a mixer for rssi??
 
So, I bought another Frsky product because the one before was shitty and now the replacement is shitty aswell. 

I hope you fix that ASAP!

A mad customer

Setup:
Qx7s Access ISMR 2.1.0
AM+
Otx 2.3.7
BF 4.2
Crazybee F4R V3

**Comment by P-I-Engineer** [comment]
i think it's all the access f.port at this point.
rx6r doesn't work either

the only one i've got to work correctly is r-xsr beta firmware from a different issue in here.

**Comment by Adelaxie** [comment]
Please check the fix from the latest firmware download from the website
