### ISSUE TITLE
XSR A2 no longer available with FW-XSR-v2.1.0.zip

### ISSUE THREAD

**Issue by Devil-67** [FrSkyRC/Firmware-Test#85]
@Adelaxie After the update to FW-XSR-v2.1.0.zip, A2 is no longer available.
Binding was also done.
All sensors deleted and searched for new did not help.
It looks like an error in firmware 2.10
It works with the V1

Please change the firmware so that A2 is available again

**Comment by Adelaxie** [comment]
Also,  only LBT involved right?

**Comment by Devil-67** [comment]
Yes LBT-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 20.07.20, 08:36 schrieb Adela <notifications@github.com>:

   
  Also, only LBT involved right?

**Comment by Devil-67** [comment]
Yes only LBT.

**Comment by Adelaxie** [comment]
Move it to #86
