### ISSUE TITLE
G-RX8 LBT 2.10

### ISSUE THREAD

**Issue by Devil-67** [FrSkyRC/Firmware-Test#9]
@Adelaxie

There are good and bad things to report.

I share the problems on something so that it is clearly.

My equipment:
Taranis X9D + with HF firmware 2.10 LBT and G-RX8 with 2.10.

issue 1.

Good thing: they improved the altimeter drift.
It looks like you have introduced an automatic zero adjustment, unfortunately it only works sometimes.
If no other sensor is connected to the S-Port, the adjustment almost always works, but as soon as an extra sensor is connected to the Sport, the zero adjustment does not always work and also takes a long time.
As a representation, I once inserted a log in which the adjustment works well without an additional sensor, takes 10 seconds.
And once the sensor is connected here, the adjustment takes about 3.5 minutes.

But you're on the right path

![ALT OK](https://user-images.githubusercontent.com/31169133/77238880-cd4f8180-6bd4-11ea-8733-8f0123cecd3a.PNG)

![ALT Error](https://user-images.githubusercontent.com/31169133/77238886-d50f2600-6bd4-11ea-9a01-e871f16f0912.PNG)

![ALT Error 2](https://user-images.githubusercontent.com/31169133/77238967-c7a66b80-6bd5-11ea-8e67-08cdc94b5541.PNG)

**Comment by Devil-67** [comment]
Hello @Adelaxie

second mistake.

My equipment:
Taranis X9D + with HF firmware 2.10 LBT and G-RX8 with 2.10.

The RSSI scaling is far too high compared to the previous firmware versions and receivers like X8R with 117db 2m Distanz.
The failsafe also comes at significantly higher values than all other receivers.
Please make it uniform
otherwise it confuses too much and may lead to a crash.

![RSSI](https://user-images.githubusercontent.com/31169133/77239132-55368b00-6bd7-11ea-99c5-43a83db2272e.PNG)

and the message sensor is lost again and again

**Comment by Devil-67** [comment]
Then there are still extreme peaks in the telemetry values.

![Peak](https://user-images.githubusercontent.com/31169133/77239434-fa069780-6bda-11ea-92b6-a137d0a32cb5.PNG)

**Comment by Devil-67** [comment]
And then there is the Lostframe counter that no longer works properly.
The counter shows 100% quality until shortly before the crash only when the link quality is almost no longer available, but the value drops, but it is already too late.

Please fix this so that we can also rely on the measured values.
urgent

![G-RX8](https://user-images.githubusercontent.com/31169133/77239893-fb868e80-6bdf-11ea-9be9-a3bca78e273a.PNG)

**Comment by 2TomTom2** [comment]
@Adelaxie I did successfully run flight test as mentioned above with same Sender, Plane and GPS Sensor but now using the G-RX8 instead of X8R with the integrated altimeter and the FW G-RX8_ACCST_2.1.0_LBT.frk. Warning Levels as mentioned 39/36. The RSSI Values similar to X8R.
**- No lost telemetry - all OK**
**- Vario is doing OK**

![Sonix_G-R8X_V2-1-0-22-03-_2020_14_17_35](https://user-images.githubusercontent.com/62436230/77253278-442e5e00-6c59-11ea-9333-fde7ce6a21da.jpg)

**Comment by Adelaxie** [comment]
> but as soon as an extra sensor is connected to the Sport, the zero adjustment does not always work and also takes a long time.

what sensor you are connecting to the G-RX8? @Devil-67

**Comment by VancouverUmbrella** [comment]
> "Then there are still extreme peaks in the telemetry values."

Confirmed the same problem in FCC. For example:

![image](https://user-images.githubusercontent.com/56514835/77280706-4527b580-6c82-11ea-9749-5b8efa33a3bb.png)

**Comment by Devil-67** [comment]
> > Sobald jedoch ein zusätzlicher Sensor an den Sport angeschlossen ist, funktioniert die Nullpunkteinstellung nicht immer und dauert auch lange.
> 
> Welchen Sensor schließen Sie an den G-RX8 an? @ Devil-67

I tested the FRsky Lipo Sensor FLVSS.
Then I checked the SM GPS Loger V2.
And finally, the LQ / LInk quality sensor based on Arduino.
it doesn't matter which sensor I connect, the error is the same for every sensor.

The message Sensor is also lost very often.

**Comment by Devil-67** [comment]
@ Adelaxie

I have behaved an update for the VSPD and Alt.

I flashed a second G-RX8 with 2.10 which showed no problem finding zero.

After that I flashed the first G-RX8 with the strange zero offset behavior with all older Frsky firmware, with the G-RX8LBT170929 and the RX behaved "normally" with the offset finding see log.
Means for me there are different hardware versions of the G-Rx8.

![G-RX8 Alte Firmware](https://user-images.githubusercontent.com/31169133/77326754-91263900-6d1a-11ea-9216-5c65738ff289.PNG)

**Comment by Adelaxie** [comment]
> Lostframe counter

what is the 5100-5104 data come from? It's a customized sensor by yourself, right? We do not see any problem in SBUS FL bit.

**Comment by Devil-67** [comment]
This is an Arduino based Lostframe counter.
Since Frsky no longer shows us the true link quality on the S-Bus, clever people have found a way to measure the real link quality using this sensor.

Here the values and explanation for the measured and recorded in the log.
Sensor application IDs
 *   5100: Good frames % of last 100 frames (Tadango method)
 *   5101: Frame Loss Counter  , absolute 32Bit value (FrSky)
 *   5102: Frame Loss Counter 2, absolute 32Bit value (@bionicbone method)
 *   5103: Good frames % of last 100 frames (@bionicbone method)
 *   5104: Test waveform from Channel 8

The problem in the S-Bus FL BIT is the following, it shows 100% link quality and that with RSSI 35 just before the failsafe? that can not be.
The sensor measures the real link quality on the S-Bus and writes it to the log.

I am attaching a diagram here again in which I have marked the critical area in red.
The value 5100 indicated the real link quality in the old firmware versions.
Frsky has changed something in the new firmware versions and it is safely weighed until shortly before the failsafe and a loss of control of the user with an "incorrect" value in the link quality.
That is not OK

![zweiter GRX-8 Link Quality Info](https://user-images.githubusercontent.com/31169133/77407451-6b4e7200-6db6-11ea-94ce-a3886f0274ed.PNG)



But you are welcome to read on RCG here the topic is discussed very exclusive and really not considered good.
[https://www.rcgroups.com/forums/showthread.php?3507071-Important-Firmware-Update-%C2%96-ACCST-D16-2-0-0-ACCESS-also-affected/page128](url)

or here the German Frsky Premium Dealer Forum, they must be registered to read
[https://frsky-forum.de/thread/3805-fl-flag-sbus-versch%C3%B6nerung-schummelvorw%C3%BCrfe-sammelbecken-f%C3%BCr-vorw%C3%BCrfe-und-handfe/?postID=44898#post44898](url)

or
[https://fpv-community.de/threads/vorsicht-bei-telemetrie-verloren-mit-horus.84554/](url)

I hope that I have expressed myself correctly, my English is not the best ;-)

**Comment by Devil-67** [comment]
As far as I know, the HF chips used by Frsky can output the LQ directly.
Perhaps Frsky should do that in ACCST and, in my opinion, ACCSSES.
Although I really don't care about accesses at the moment, like many people, there are simply serious errors in both systems that keep me and many others from buying at the moment.
Frsky was supposed to restore his image sleepily.
That is just my opinion as a longtime Frsky user who is slowly becoming very angry and insecure.

**Comment by bionicbone** [comment]
@Adelaxie 

Essentially the community would like FrSky to update the SBUS FL bit like this, it is how the original v1 on the older Rx's worked. With the introduction of v2 we can see that the FL Bit is not set high until 4 consecutive frame have been lost. We would prefer early warning rather than a last minute warning.

![image](https://user-images.githubusercontent.com/7845867/77416852-55dc4680-6dbc-11ea-98bf-ee5ac2f5cfbf.png)

**Comment by franz4949** [comment]
@Adelaxie 
Why does FrSky manipulate the LF bit in the SBus stream? What is FrSky problem with letting the LF bit untouched as it is in all v1 ACCST firmware. And what is the benefit for the user to have the LF bit manipulated in v2 ACCST? And what is the benefit for FrSky to insist on the manipulated LF bit?? Many questions and hopefully answers to them from FrSky.

**Comment by VancouverUmbrella** [comment]
> Bottom line we request a one to one relationship between a dropped / rejected RF frame and the FL Flag set in the SBUS output.

Yes, this is certainly my wish.

As things stand in D16 v2.1.0, the manipulated SBUS LF data do not seem to provide an accurate and reliable indication of actual link quality.

**Comment by Adelaxie** [comment]
> The value 5100 indicated the real link quality in the old firmware versions.
Frsky has changed something in the new firmware versions and it is safely weighed until shortly before the failsafe and a loss of control of the user with an "incorrect" value in the link quality.

So the diagram is showing the old firmware(v2.0.1) behavior? Maybe I missed it, where can I find the diagram with firmware that we are testing here?

**Comment by Adelaxie** [comment]
The telemetry data peak issue is confirmed.

**Comment by Adelaxie** [comment]
confirmed and please check #13 as a brief conclusion

**Comment by Adelaxie** [comment]
Please check the G-RX6/G-RX8 updates on #13 posts.

**Comment by FlorianReck** [comment]
Hello all,
the vario behaviour is worse than before. Here the Pics an Logs:

Firmware: From FrSky, 2.1.0, OTX 2.3.7

V1:
![GRX8_V1](https://user-images.githubusercontent.com/4091312/80908944-6a4d2080-8d24-11ea-8299-21497315a416.png)

LogFile
[MODEL01-2020-05-02.csv.txt](https://github.com/FrSkyRC/Firmware-Test/files/4569782/MODEL01-2020-05-02.csv.txt)

V2:
![GRX8](https://user-images.githubusercontent.com/4091312/80908966-8a7cdf80-8d24-11ea-9520-6b4d8d66547b.png)

LogFile:
[Wandervogel-2020-05-01.csv.txt](https://github.com/FrSkyRC/Firmware-Test/files/4569783/Wandervogel-2020-05-01.csv.txt)

It looks very noisy on V2. Please take the HP vario as refernence, or at least like it was before.

This is unfiltered, I know about the "workaround", but wyh use a workarounnd if the root cause can be fixed?

Florian

**Comment by VancouverUmbrella** [comment]
I see the same fluctuations in logfiles from a G-RX8 running 2.1.0E.

We now understand that 2.1.0E is the version that was published on the FrSky as the official release.
