### ISSUE TITLE
Archer R8 pro, FW Archer-X_2.1.2: not in S.Port mode after update

### ISSUE THREAD

**Issue by RetoD7** [FrSkyRC/Firmware-Test#96]
After updating from 2.1.0 to 2.1.2 the S.Port is not working anymore. It seems to be in F.Port mode even the option tells it should be S.Port.
Switching to F.Port and back to S.Port mode solves the problem.

By the way: version still shows 2.1.0

**Comment by Adelaxie** [comment]
> It seems to be in F.Port mode even the option tells it should be S.Port.
Switching to F.Port and back to S.Port mode solves the problem.

will fix it at the radio end.

**Comment by RetoD7** [comment]
Seems okay with FW Archer-X_2.1.5.
